services:
  postgres:
    image: postgres:16-alpine
    container_name: desafio-elite-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-desafio_elite}
      POSTGRES_USER: ${POSTGRES_USER:-desafio}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-desafio}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - postgres_homolog_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER:-desafio} -d ${POSTGRES_DB:-desafio_elite}',
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_homolog_data:
    driver: local
